version: '3'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - appnet

    
  api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:Default=Server=sql,1433;Database=eBus;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 64236:80
    networks:
      - appnet
      
networks:
  appnet:
    driver: bridge